[package]
name = "ghaggs-joelsi-project"
version = "0.1.0"
edition = "2024"

[dependencies]
ggez = "0.9.3"
rand = "0.9.1"
itertools = "0.14.0"
poker_eval = "0.1.0"
strum = "0.27.1"
strum_macros = "0.27.1"